# Generated by Django 3.2.4 on 2021-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('engine_status', models.CharField(choices=[('WS', 'WORKS SMOOTHLY'), ('WN', 'WORKING NORMAL'), ('WP', 'WORKING PROBLEM'), ('VB', 'VEHICLE BROKEN')], default='WN', max_length=2)),
                ('engine', models.CharField(max_length=60)),
                ('temperature', models.FloatField()),
                ('fuel_status', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=6)),
                ('speed', models.FloatField()),
                ('total_traveled', models.FloatField(default=0)),
                ('total_traveled_time', models.FloatField()),
                ('colour', models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('OTHER', 'OTHER')], default='BLACK', max_length=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
