# Generated by Django 3.2.4 on 2021-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_status',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_status',
            field=models.CharField(choices=[('WORKS SMOOTHLY', 'WORKS SMOOTHLY'), ('WORKING NORMAL', 'WORKING NORMAL'), ('WORKING PROBLEM', 'WORKING PROBLEM'), ('VEHICLE BROKEN', 'VEHICLE BROKEN')], default='WN', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(verbose_name='speed(km/h)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='total_traveled',
            field=models.FloatField(default=0, verbose_name='total traveled (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='total_traveled_time',
            field=models.FloatField(verbose_name='total traveled time(hour)'),
        ),
    ]
